# Generated by Django 5.2.11 on 2026-02-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='emotion_score',
        ),
    ]
