# Generated by Django 5.2.11 on 2026-02-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_diaryentry_emotion_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='physical_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
